[plugin]
repository = "https://github.com/spide-r/PvPAnnouncer.git"
commit = "57a776a6d5ca92d2e8657f26ff05260f119b6433"
owners = ["spide-r"]
project_path = "PvPAnnouncer"
changelog = "Metem's Battle talk now shows up when he speaks!"
